2023-06-13 08:28:43,277 INFO    MainThread:744413 [wandb_setup.py:_flush():76] Current SDK version is 0.15.3
2023-06-13 08:28:43,278 INFO    MainThread:744413 [wandb_setup.py:_flush():76] Configure stats pid to 744413
2023-06-13 08:28:43,278 INFO    MainThread:744413 [wandb_setup.py:_flush():76] Loading settings from /home/edo/.config/wandb/settings
2023-06-13 08:28:43,278 INFO    MainThread:744413 [wandb_setup.py:_flush():76] Loading settings from /home/edo/Desktop/orc/03_assignment/wandb/settings
2023-06-13 08:28:43,278 INFO    MainThread:744413 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'_executable': '/usr/bin/python3'}
2023-06-13 08:28:43,278 INFO    MainThread:744413 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'DQN template.py', 'program': 'DQN template.py'}
2023-06-13 08:28:43,278 INFO    MainThread:744413 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-06-13 08:28:43,278 INFO    MainThread:744413 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-06-13 08:28:43,278 INFO    MainThread:744413 [wandb_init.py:_log_setup():507] Logging user logs to /home/edo/Desktop/orc/03_assignment/wandb/run-20230613_082843-8nwwh9a1/logs/debug.log
2023-06-13 08:28:43,278 INFO    MainThread:744413 [wandb_init.py:_log_setup():508] Logging internal logs to /home/edo/Desktop/orc/03_assignment/wandb/run-20230613_082843-8nwwh9a1/logs/debug-internal.log
2023-06-13 08:28:43,279 INFO    MainThread:744413 [wandb_init.py:init():547] calling init triggers
2023-06-13 08:28:43,279 INFO    MainThread:744413 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-06-13 08:28:43,279 INFO    MainThread:744413 [wandb_init.py:init():596] starting backend
2023-06-13 08:28:43,279 INFO    MainThread:744413 [wandb_init.py:init():600] setting up manager
2023-06-13 08:28:43,283 INFO    MainThread:744413 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-13 08:28:43,287 INFO    MainThread:744413 [wandb_init.py:init():606] backend started and connected
2023-06-13 08:28:43,291 INFO    MainThread:744413 [wandb_init.py:init():700] updated telemetry
2023-06-13 08:28:43,313 INFO    MainThread:744413 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-06-13 08:29:43,342 ERROR   MainThread:744413 [wandb_init.py:init():763] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-06-13 08:29:43,370 ERROR   MainThread:744413 [wandb_init.py:init():1168] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/edo/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
  File "/home/edo/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 769, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-06-13 08:29:44,398 WARNING MsgRouterThr:744413 [router.py:message_loop():77] message_loop has been closed
